DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS CATEGORYS CASCADE;
DROP TABLE IF EXISTS PARTICIPATION_REQUESTS CASCADE;
DROP TABLE IF EXISTS EVENTS CASCADE;



CREATE TABLE IF NOT EXISTS USERS
(
    ID                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    USER_NAME                 VARCHAR(255)                            NOT NULL,
    USER_EMAIL                VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS CATEGORYS
(
    ID                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CATEGORY_NAME             VARCHAR(500)                            NOT NULL,
    CONSTRAINT PK_CATEGORY   PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS EVENTS
(
    ID                        BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    ANNOTATION                VARCHAR                          ,
    CATEGORY_ID               INTEGER                                 ,
    CONFIMED_REQUESTS         INTEGER                                 ,
    CREATED_ON                TIMESTAMP WITHOUT TIME ZONE             ,
    DESCRIPTION               VARCHAR                           ,
    EVENT_DATE                TIMESTAMP WITHOUT TIME ZONE             ,
    USER_ID                   INTEGER                                 ,
    LAT                       FLOAT                                   ,
    LON                       FLOAT                                   ,
    PAID                      BOOLEAN                                 ,
    PARTICIPANT_LIMIT         INTEGER                                 ,
    PUBLISHED_ON              TIMESTAMP WITHOUT TIME ZONE             ,
    REQUEST_MODERATION        BOOLEAN                                 ,
    EVENTS_STATE              VARCHAR(40)                            ,
    TITLE                     VARCHAR(120)                            ,
    VIEWS                     INTEGER                                 ,

    CONSTRAINT PK_EVENTS   PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS PARTICIPATION_REQUESTS
(
    ID                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CREATED                   TIMESTAMP WITHOUT TIME ZONE,
    EVENT                     INTEGER                                 NOT NULL,
    REQUESTER                 INTEGER                                 NOT NULL,
    STATUS                    VARCHAR(255)                            NOT NULL,

    CONSTRAINT PK_PARTICIPATION_REQUESTS PRIMARY KEY (ID)
    );


